hw1 is done
Askaell/homework pull request #1
Opened 2021-04-14 07:55 UTC by Askaell

2021-04-15 19:43 UTC, goarchitecture requested changes
Общий комментарий:

Очень хорошо. Я расставил комментарии к строкам кода. 

Комментарит помеченные "^__^" - это side-comments - не относящиеся строго к основной теме (Архитектура, разделение логики и БД). 

Там всего пару непомеченных комментариев, относящихся к теме урока. По сути там немного лишнех оболочек и сложности нейминга. А так с задачей разделить логику и БД справились.

2021-04-15 19:43 UTC, goarchitecture commented on .gitignore
> +.DS_Store
.gitignore побогаче можно сделать, посмотри на гитхабе что часто добавляют. 
(к примеру папки от IDE, приватные env и конфиг файлые и бинарники)

^_^

2021-04-15 19:43 UTC, goarchitecture commented on cmd/main.go
> +	GoArchitecture "github.com/Askaell/homework"
в go не принято пакеты с заглавных начинать

^__^

2021-04-15 19:43 UTC, goarchitecture commented on cmd/main.go
> +	services := service.NewService(repository)
небольшая несостыковка. NewService а переменная `serviceS` (так там одна служба или несколько служб создаются?) тоже самое с handlers.

Ещё про нейминг: сервис из пакета с имением "service" это как пиво с этикеткой "пиво". Надо дать ему имя всё-таки. что за служба? какой use-case решает, или какой сущности служит (ItemService к примеру и т.д.)

^__^

2021-04-15 19:43 UTC, goarchitecture commented on configs/config.yaml
> +port: "8000"
Обсуждаем в лекции 2:

не храним настоящие конфиги в папке `configs`.
Но и просто скрыть конфиг - не показательно, мы хотим видить его структуру. Для этого нужно хранить здесь шаблон (или пример) конфига.
(а .gitignore поможет спрятать этот настоящий конфиг)

2021-04-15 19:43 UTC, goarchitecture commented on go.mod
> +go 1.14
на новых проектах все лучше использовать последний go


^__^

2021-04-15 19:43 UTC, goarchitecture commented on handler/handler.go
> +	services *service.Service
обсуждали выше проблему нейминга: `serviceS`

^__^

2021-04-15 19:43 UTC, goarchitecture commented on handler/item.go
> +	c.JSON(http.StatusOK, map[string]interface{}{
нет нужны перемэпить объект из модели в map[string]interface{}
Возвращай прямо настоящий объект

^__^

2021-04-15 19:43 UTC, goarchitecture commented on handler/item.go
> +	c.JSON(http.StatusOK, getAllItemsResponse{
пока конверт не понадобился по какой-то причине - его лучше и недобавлять. 
Конверты добавляют только когда они действительно нужны (пагинация и т.д.).

^__^

2021-04-15 19:43 UTC, goarchitecture commented on handler/item.go
> +	c.JSON(http.StatusOK, statusResponse{
по REST обычно DELETE возвращает 0 байт в ответ с кодом 204

^__^

2021-04-15 19:43 UTC, goarchitecture commented on repository/repository.go
> +type Item interface {
`Item` название для модели, но не для интерфейса репозитория. Не интуитивное название

^__^

2021-04-15 19:43 UTC, goarchitecture commented on repository/repository.go
> +	Item
Знаю, так много делали раньше, я тоже так любил делать. Но этот лишний конверт, только добавляет ненужный дополнительный уровень.

Легче просто сделать структуру которая следует интерфейса (у тебя по сути такая структура уже есть - ItemPostgres).
Получается что здесь Repository - добавлен просто как атавизм. (Это из-за путаницы в нейминге)

^__^

2021-04-15 19:43 UTC, goarchitecture commented on service/item.go
> +func NewItemService(repository repository.Item) *ItemService {
Служба в принципе во всей этой архитектуре - лишняя.

Обычно, когда контроллеры (handlerы) разрастаются, есть смысл их логику делить на use-case и обрамлять их в службы. 
Но в нашем случае, handler может напрямую оперировать репозиторием, так как логики дополнительной как таковой нет.

А служба которая ничего кроме вызова репозитория не делает - просто добавляет лишнюю оболочку.

*Сложность надо решать, а не добавлять. Добавлять сложность надо только когда это действительно необходимо"

2021-04-17 06:30 UTC, Askaell commented on handler/item.go
> +	c.JSON(http.StatusOK, statusResponse{
я правильно понял, что тогда нужно делать вот так:
`c.JSON(http.StatusNoContent, nil)`
?

2021-04-17 06:31 UTC, Askaell commented on handler/item.go
> +	c.JSON(http.StatusOK, statusResponse{
но я не уверен, что `nil` вернет 0 байт...

2021-04-18 07:04 UTC, Askaell commented on repository/repository.go
> +	Item
Простите, не совсем понимаю, что вы имеете ввиду...

тут структура Repository создана для того, чтобы мы имели возможность инициализируя только эту структуру, сразу инициализировать и все входящие в неё репозитории (если бы у нас были ещё какие-либо репозитории помимо репозитория Item)

а если убрать эту структуру, то получится, что каждый репозиторий придется инициализировать вручную в main...

2021-04-18 07:21 UTC, Askaell commented on service/item.go
> +func NewItemService(repository repository.Item) *ItemService {
я согласен, что сейчас это избыточно, но во второй лекции вы тоже создали сервис, когда показывали пример каркаса приложения -  я думал, что мы будем как-то расширять функциональность, но если они нам не понадобятся в следующих уроках, то тогда я их уберу

2021-04-20 18:58 UTC, goarchitecture commented on repository/repository.go
> +	Item
Каждый репозиторий и нужно инициализировать отдельно.
Допустим у вас 10 сущностей: Item, Order, User, Gift, ....
Казалось бы, что если  синицилизировать один объект Repository{ Item, Order, User, Gift  ...}, То вы упростите себе жизнь, на самом деле - нет, усложните.

1) Вы привязываете все сущности к одному типу ДЗ. На деле же они все могут быть разным БД. И если так - то конструирование такой общей Repository{} становится более сложным
2) Вы тащите с собой всегда все 10 репозиториев, когда иногда вам нужна только одна.

Для этого как раз и есть паттерн Фабрика - что можно тащить с собой фабрику, а она создаст вам нужную репозиторию всегда. Но сразу инициализировать все репозитории, врапить их в один объект и тоскать его как зависимость с собой - только усложнит вам жизнь в большом проекте

2021-04-20 19:00 UTC, goarchitecture commented on service/item.go
> +func NewItemService(repository repository.Item) *ItemService {
Да, я принимаю, что сервис вообще - нужный слой абстракции между контроллером и репой.

Но так же есть такой паттерн разработки - когда по дефолту мы всегда выбираем самое простое решение, а добавляем уровни абстракции при необходимости (тем более здесь нам это пока просто как лишний копи-пейст, который усложняет код, а когда сервис реально понадобится - рефакторинг будет каких-то 10-15 минут)

2021-04-21 13:40 UTC, merged