hw-4 is done
Askaell/homework pull request #4
Opened 2021-04-26 17:34 UTC by Askaell

2021-05-05 15:35 UTC, goarchitecture requested changes

2021-05-05 15:35 UTC, goarchitecture commented on pkg/handler/item.go
> +func (h *Handler) updateItem(c *gin.Context) {
Update на уровне Handler-а можно оставить, но нужно понмиать, что он не нужен для данной задачи. DiscountService может напрямую использовать Repository, а не handler

2021-05-05 15:35 UTC, goarchitecture commented on pkg/repository/item_postgres.go
> +	if item.Name != "" {
как только в модель Item-а добавится филд, этот метод станется неполноценным (ведущим к багам).
Конечно, можно просто "не забывать" и всегда обновлять этот метод, но есть идеи как решить эту проблему? (исправлять не обязательно, просто вопрос на раздумывание)

2021-05-05 15:35 UTC, goarchitecture commented on pkg/service/discount_service/discount_service.go
> +	items, err := s.repository.GetAll()
дайте больше гибкости. пусть items  будет параметром в applyDiscounts
Тогда мы можем вызывать эту функцию для ограниченного числа итемов

2021-05-05 15:35 UTC, goarchitecture commented on pkg/service/discount_service/discount_service.go
> +			time.Sleep(24 * time.Hour)
если applyDiscounts займет больше 1 минуты, то sleep 24 time.Hour "перемотает" слишком далеко и следующий раз таск не пройдет.

Советую не делать time.Sleep здесь вообще.
А просто выше сделать правильную проверку (и continue во всех других случаях)

2021-05-07 16:08 UTC, Askaell commented on pkg/repository/item_postgres.go
> +	if item.Name != "" {
мне приходит в голову только создать специальный сервис для валидации входного item'a, но там тоже придётся не забывать его обновлять, поэтому пока что идей нет...

буду вам благодарен, если подскажете, как это сделать более оптимально)

2021-05-11 13:36 UTC, merged