hw-5 is done
Askaell/homework pull request #5
Opened 2021-04-29 09:48 UTC by Askaell

2021-05-01 02:58 UTC, goarchitecture requested changes
Хороший старт, но не до конца.

2021-05-01 02:58 UTC, goarchitecture commented on pkg/models/category.go
> +		c.ParentId = id
сама на себя?
у того, у кого нет родителя - и не должно быть его.

(Я понимаю, что это будет работать, но проверка `c.Parent == nil` понятнее чем `c.Parent == c`

2021-05-01 02:58 UTC, goarchitecture commented on pkg/models/category.go
> +func (c *Category) GetBreadCrumbs() []*Category {
если тип-коллекции дать своё название, то можно добавить вспомогательные методы типа .Slugs()/ .Names()

В теории хотелось бы такое использование:
```
breadCrumbsLabel := strings.Join(c.GetBreadCrumbs().Names(), " / ")

2021-05-01 02:58 UTC, goarchitecture commented on pkg/models/category.go
> +type Category struct {
не хватает метода добавления подкатегории в категорию.
Parent/ParentId/Childs нигде (кроме главного New) не назначается, только читается

2021-05-02 07:20 UTC, Askaell commented on pkg/models/category.go
> +type Category struct {
исправил, теперь при вызове NewCategory, если был указан parent, то новая категория будет добавлена в childs данного родителя

2021-05-02 07:22 UTC, Askaell commented on pkg/models/category.go
> +func (c *Category) GetBreadCrumbs() []*Category {
создал `type Categories []*Category` и добавил к нему данные методы

2021-05-02 07:24 UTC, Askaell commented on pkg/models/category.go
> +		c.ParentId = id
исправил, теперь:
`if parent == nil {
		c.ParentId = 0
		c.Parent = nil
		return c
}`

2021-05-08 06:04 UTC, goarchitecture commented
Добавьте пару базовых тестов, чтобы убедиться что точно работает (к примеру создайте 3 категории и вызовите Breadcrumbs)

2021-05-11 13:35 UTC, merged